# Generated by Django 3.2.22 on 2023-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20231007_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='generated_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
