# Generated by Django 3.2.22 on 2023-10-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournament.match'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournament.participant'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournament.participant'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournament.tournament'),
        ),
    ]
