# Generated by Django 3.2.22 on 2023-10-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20231007_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winning_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.participant'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
